export const PHONE_LIST_REQUEST = "PHONE_LIST_REQUEST";
export const PHONE_LIST_SUCCESS = "PHONE_LIST_SUCCESS";
export const PHONE_LIST_FAIL = "PHONE_LIST_FAIL";

export const PHONE_DELETE_REQUEST = "PHONE_DELETE_REQUEST";
export const PHONE_DELETE_SUCCESS = "PHONE_DELETE_SUCCESS";
export const PHONE_DELETE_FAIL = "PHONE_DELETE_FAIL";
